name: Test CI

on:
   push:
        branches: [master]
   pull_request:
        branches: [master]
      
jobs:
    build_job:
      runs-on: ubuntu-lastest
      
      steps:
        - uses: actions/checkout@v2
        - name: Auto build when push
        - run: echo this is a test yml file for build project!
        - run: npm run build
