name: Test CI

on: 
    push:
        branches: [master]


jobs:
    first_job:
            name: First Job
            runs-on: ubuntu-18.04
            steps:
              - uses: actions/checkout@v2
              - uses: actions/setup-node@v1
              - uses: bahmutov/npm-install@v1
              - run: npm run lint
    second_job:
            name: Second Job
            runs-on: ubuntu-18.04
            steps:
              - uses: actions/checkout@v2
              - uses: actions/setup-node@v1
              - uses: bahmutov/npm-install@v1
              - run: npm run build        
    third_job:
            name: Third Job
            run: echo The third job!!      

            