name: Test CI

on:
   push:
        branches: [master]
   pull_request:
        branches: [master]
      
jobs:
    build_job:
      runs-on: ubuntu-lastest
      
      steps:
    
      # 定义 step 的环境变量
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      # 运行指令：输出环境变量
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
