name: Test CI

on: 
     push:
          branches: [master]

jobs:
     build_job:
          runs-on: ubuntu-lastest
          name: Build Job
          steps:  
               - name: push operate
               run: echo push master
               run: npm run build