name: Test CI

on: 
     push:
          branches: [master]

jobs:
     build_job:
          name: Build Job
          runs-on: ubuntu-lastest
          steps:  
          - name: push operate
            run: echo push master
            run: npm run build