name: Test CI

on: 
     push:
          branches: [master]

jobs:
     build_job:
          name: Build Job
          runs-on: ubuntu-lastest
          steps:  
          - name: echo line
            run: echo push master
          - name: try to build
            run: npm run build