name: Test CI

on: 
     push:
          branches: [master]

jobs:
     lint:
          runs-on: ubuntu-18.04
          steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v1
            with:
               node-version: "14.x"
          - name: Install dependencies
            uses: bahmutov/npm-install@v1

          - name: Run linter
            run: npm run lint
     build:
          name: Build Job
          runs-on: ubuntu-lastest
          steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v1
            with: 
                node-version: "14.x"
          - name: Install dependecies
            uses: bahmutov/npm-install@v1
          
          - run: npm install
          - run: npm test
          - run: npm build